[tool.poetry]
name = "tailucas-pylib"
version = "0.2.8"
description = "Common Python utility modules"
authors = ["Tai Lucas <tglucas@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
botoflow = "^0.8"
boto3 = "^1.34.93"
cronitor = "^4.7.1"
msgpack = "^1.0.8"
onepasswordconnectsdk = "^1.5.1"
pika = "^1.3.2"
python-dateutil = "^2.9.0.post0"
pytz = "^2024.1"
pyzmq = "^26.0.2"
sentry-sdk = "^2.0.1"
simplejson = "^3.19.2"
pyyaml = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
